//
// Created by xgallom on 4/26/20.
//

#ifndef XALGO_ROOT_XALGO_INCLUDE_XALGO_WORKSPACE_WORKSPACE_FWD_H
#define XALGO_ROOT_XALGO_INCLUDE_XALGO_WORKSPACE_WORKSPACE_FWD_H

namespace xalgo::Workspace {
	struct Class;
}

#endif //XALGO_ROOT_XALGO_INCLUDE_XALGO_WORKSPACE_WORKSPACE_FWD_H
